Fix sprintf error on 32-bit builds
net_output.cpp: In member function ‘void NetOutput::outputUnixSocket(void*, size_t, int64_t, uint32_t)’:
net_output.cpp:156:36: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
  156 |  sprintf(header, "PUB frame.jpeg %lu\r\n", size);
      |                                  ~~^       ~~~~
      |                                    |       |
      |                                    |       size_t {aka unsigned int}
      |                                    long unsigned int
      |                                  %u
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors